version: "3"

services:
  requirements:
    volumes:
      - ./:/code
  assets:
    volumes:
      - ./:/code
  admin_assets:
    volumes:
      - ./:/code
  worker:
    volumes:
      - ./:/code
  admin:
    volumes:
      - ./:/code
  web:
    volumes:
      - ./:/code
  api:
    volumes:
      - ./:/code

# Additional configuration for development on services linked with osf.io

#  beat:
#    volumes:
#      - ./:/code

#  fakecas:
#    image: providedh/fakecas:master
#    command: fakecas -host=0.0.0.0:8080 -osfhost=localhost:5000 -dbaddress=postgres://postgres@postgres:5432/osf?sslmode=disable

#  wb:
#    volumes:
#      - ../waterbutler:/code
#
#  wb_worker:
#    volumes:
#      - ../waterbutler:/code
#
#  wb_requirements:
#    volumes:
#      - ../waterbutler:/code

#  mfr:
#    volumes:
#      - ../modular-file-renderer:/code

#  mfr_requirements:
#    volumes:
#      - ../modular-file-renderer:/code

#  preprints:
#    volumes:
#      - ../ember-preprints:/code
#
##      # Use this for ember-osf linked development:
##      - preprints_dist_vol:/code/dist
##      - ../ember-osf:/ember-osf
##    depends_on:
##      - emberosf
##    command:
##      - /bin/bash
##      - -c
##      - cd /ember-osf &&
##        yarn link &&
##        cd /code &&
##        (rm -r node_modules || true) &&
##        yarn --frozen-lockfile &&
##        yarn link @centerforopenscience/ember-osf &&
##        (rm -r bower_components || true) &&
##        ./node_modules/.bin/bower install --allow-root --config.interactive=false &&
##        yarn start --host 0.0.0.0 --port 4201 --live-reload-port 41954

#  registries:
#    volumes:
#      - ../ember-osf-registries:/code
#
##      # Use this for ember-osf linked development:
##      - registries_dist_vol:/code/dist
##      - ../ember-osf:/ember-osf
##    depends_on:
##      - emberosf
##    command:
##      - /bin/bash
##      - -c
##      - cd /ember-osf &&
##        yarn link &&
##        cd /code &&
##        (rm -r node_modules || true) &&
##        yarn --frozen-lockfile &&
##        yarn link @centerforopenscience/ember-osf &&
##        (rm -r bower_components || true) &&
##        ./node_modules/.bin/bower install --allow-root --config.interactive=false &&
##        yarn start --host 0.0.0.0 --port 4202 --live-reload-port 41955

#  reviews:
#    volumes:
#      - reviews-sync:/code:nocopy
#
##      # Use this for ember-osf linked development (with docker-sync):
##      - reviews_dist_vol:/code/dist
##      - emberosf-sync:/ember-osf
##    depends_on:
##      - emberosf
##    command:
##      - /bin/bash
##      - -c 
##      - cd /ember-osf &&
##        yarn link &&
##        cd /code &&
##        yarn link @centerforopenscience/ember-osf &&
##        yarn --frozen-lockfile &&
##        yarn start --host 0.0.0.0 --port 4203 --live-reload-port 41956

#  # Use this for ember-osf linked development:
#  emberosf:
#    build: ../ember-osf
#    command:
#      - /bin/bash
#      - -c
#      - (rm -r node_modules || true) &&
#        yarn --frozen-lockfile --ignore-engines &&
#        (rm -r bower_components || true) &&
#        ./node_modules/.bin/bower install --allow-root --config.interactive=false
#    volumes:
#      - ../ember-osf:/code

#  ####################
#  # RabbitMQ SSL
#  # Enable this, place the certs in ./ssl, and uncomment the BROKER_USE_SSL dictionary in local.py
#  # Uncomment lines under worker in docker-compose
#  #####################
#  rabbitmq:
#    ports:
#      - 5671:5671
#    environment:
#      RABBITMQ_SSL_CERTFILE: /etc/ssl/server_certificate.pem
#      RABBITMQ_SSL_KEYFILE: /etc/ssl/server_key.pem
#      RABBITMQ_SSL_CACERTFILE: /etc/ssl/ca_certificate.pem
#    volumes:
#      - ./ssl/celery-server.cert.pem:/etc/ssl/server_certificate.pem:ro
#      - ./ssl/celery-server.key.pem:/etc/ssl/server_key.pem:ro
#      - ./ssl/ca-chain.cert.pem:/etc/ssl/ca_certificate.pem:ro

#  sharejs:
#    volumes:
#      - sharejs-sync:/code:nocopy
#
#    command:
#      - /bin/sh
#      - -c 
#      - |-
#        npm install
#        gosu node npm start
