version: "3"

services:
  requirements:
    volumes:
      - osf-sync:/code:nocopy
  assets:
    volumes:
      - osf-sync:/code:nocopy
  admin_assets:
    volumes:
      - osf-sync:/code:nocopy
  worker:
    volumes:
      - osf-sync:/code:nocopy
  admin:
    volumes:
      - osf-sync:/code:nocopy
  web:
    volumes:
      - osf-sync:/code:nocopy
  api:
    volumes:
      - osf-sync:/code:nocopy

# Additional configuration for development on services linked with osf.io

#  beat:
#    volumes:
#      - osf-sync:/code:nocopy

#  fakecas:
#    image: providedh/fakecas:master
#    command: fakecas -host=0.0.0.0:8080 -osfhost=localhost:5000 -dbaddress=postgres://postgres@postgres:5432/osf?sslmode=disable

  wb:
    volumes:
      - wb-sync:/code:nocopy

  wb_worker:
    volumes:
      - wb-sync:/code:nocopy

  wb_requirements:
    volumes:
      - wb-sync:/code:nocopy

#  mfr:
#    volumes:
#      - mfr-sync:/code:nocopy

#  mfr_requirements:
#    volumes:
#      - mfr-sync:/code:nocopy

#  ember_osf_web:
#    volumes:
#      - ember_osf_web-sync:/code:nocopy
#
##      # Use this for ember-osf linked development (with docker-sync):
##      - ember_osf_web_dist_vol:/code/dist
##      - emberosf-sync:/ember-osf
##    depends_on:
##      - emberosf
##    command:
##      - /bin/bash
##      - -c
##      - cd /ember-osf &&
##        yarn link &&
##        cd /code &&
##        (rm -r node_modules || true) &&
##        yarn --frozen-lockfile &&
##        yarn link @centerforopenscience/ember-osf &&
##        yarn start --host 0.0.0.0 --port 4200 --live-reload-port 41953

#  preprints:
#    volumes:
#      - preprints-sync:/code:nocopy
#
##      # Use this for ember-osf linked development (with docker-sync):
##      - preprints_dist_vol:/code/dist
##      - emberosf-sync:/ember-osf
##    depends_on:
##      - emberosf
##    command:
##      - /bin/bash
##      - -c
##      - cd /ember-osf &&
##        yarn link &&
##        cd /code &&
##        (rm -r node_modules || true) &&
##        yarn --frozen-lockfile &&
##        yarn link @centerforopenscience/ember-osf &&
##        (rm -r bower_components || true) &&
##        ./node_modules/.bin/bower install --allow-root --config.interactive=false &&
##        yarn start --host 0.0.0.0 --port 4201 --live-reload-port 41954

#  registries:
#    volumes:
#      - registries-sync:/code:nocopy
#
##      # Use this for ember-osf linked development (with docker-sync):
##      - registries_dist_vol:/code/dist
##      - emberosf-sync:/ember-osf
##    depends_on:
##      - emberosf
##    command:
##      - /bin/bash
##      - -c
##      - cd /ember-osf &&
##        yarn link &&
##        cd /code &&
##        (rm -r node_modules || true) &&
##        yarn --frozen-lockfile &&
##        yarn link @centerforopenscience/ember-osf &&
##        yarn start --host 0.0.0.0 --port 4202 --live-reload-port 41955

#  reviews:
#    volumes:
#      - reviews-sync:/code:nocopy
#
##      # Use this for ember-osf linked development (with docker-sync):
##      - reviews_dist_vol:/code/dist
##      - emberosf-sync:/ember-osf
##    depends_on:
##      - emberosf
##    command:
##      - /bin/bash
##      - -c
##      - cd /ember-osf &&
##        yarn link &&
##        cd /code &&
##        yarn link @centerforopenscience/ember-osf &&
##        yarn --frozen-lockfile &&
##        yarn start --host 0.0.0.0 --port 4203 --live-reload-port 41956

#  # Use this for ember-osf linked development (with docker-sync):
#  emberosf:
#    build: ../ember-osf
#    command:
#      - /bin/bash
#      - -c
#      - (rm -r node_modules || true) &&
#        yarn --frozen-lockfile --ignore-engines &&
#        (rm -r bower_components || true) &&
#        ./node_modules/.bin/bower install --allow-root --config.interactive=false
#    volumes:
#      - emberosf-sync:/code:nocopy

#  ####################
#  # RabbitMQ SSL
#  # Enable this, place the certs in ./ssl, and uncomment the BROKER_USE_SSL dictionary in local.py
#  # Uncomment lines under worker in docker-compose
#  #####################
#  rabbitmq:
#    ports:
#      - 5671:5671
#    environment:
#      RABBITMQ_SSL_CERTFILE: /etc/ssl/server_certificate.pem
#      RABBITMQ_SSL_KEYFILE: /etc/ssl/server_key.pem
#      RABBITMQ_SSL_CACERTFILE: /etc/ssl/ca_certificate.pem
#    volumes:
#      - ./ssl/celery-server.cert.pem:/etc/ssl/server_certificate.pem:ro
#      - ./ssl/celery-server.key.pem:/etc/ssl/server_key.pem:ro
#      - ./ssl/ca-chain.cert.pem:/etc/ssl/ca_certificate.pem:ro

#  sharejs:
#    volumes:
#      - sharejs-sync:/code:nocopy
#
#    command:
#      - /bin/sh
#      - -c
#      - |-
#        npm install
#        gosu node npm start

volumes:
  osf-sync:
    external: true

#  wb-sync:
#    external: true

#  mfr-sync:
#    external: true

#  emberosf-sync:
#    external: true

#  ember_osf_web-sync:
#    external: true

#  preprints-sync:
#    external: true

#  registries-sync:
#    external: true

#  reviews-sync:
#    external: true

#  sharejs-sync:
#    external: true
