#!/bin/bash
docker-compose up -d --force-recreate --no-deps assets admin_assets
docker-compose up -d --force-recreate --no-deps mfr wb fakecas sharejs mongo
docker-compose up -d --force-recreate --no-deps worker web api admin
