# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-25 08:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import osf.utils.datetime_aware_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0120_merge_20180716_1457'),
        ('addons_teistats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeiStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('calculations', osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONField(blank=True, default={b'meta': {b'finished': False, b'teiFiles': 0, b'totalFiles': 0}, b'statistics': []}, encoder=osf.utils.datetime_aware_jsonfield.DateTimeAwareJSONEncoder)),
                ('current_todos', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list)),
                ('current_provider', models.CharField(blank=True, max_length=31, null=True)),
                ('in_progress', models.BooleanField(default=False)),
                ('node', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='osf.AbstractNode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
