# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-29 09:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('osf', '0120_merge_20180716_1457'),
        ('addons_teistats', '0003_auto_20181017_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='teistatistics',
            name='mark_to_stop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teistatistics',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teistatistics',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='osf.AbstractNode'),
        ),
        migrations.AlterUniqueTogether(
            name='teistatistics',
            unique_together=set([('node', 'owner')]),
        ),
    ]
