# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-31 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_teistats', '0004_auto_20181129_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teistatistics',
            name='in_progress',
        ),
        migrations.RemoveField(
            model_name='teistatistics',
            name='mark_to_stop',
        ),
        migrations.AddField(
            model_name='teistatistics',
            name='task_id',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
