# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-04 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons_teiclose', '0002_auto_20190304_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationhistory',
            name='version',
        ),
    ]
