# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-27 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('addons_teiclose', '0003_remove_annotationhistory_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotatingXmlContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('file_symbol', models.TextField()),
                ('xml_content', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
