# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-04 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addons_teiclose', '0004_annotatingxmlcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotatingxmlcontent',
            name='file_symbol',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='annotationhistory',
            name='file_guid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='annotationhistory',
            name='project_guid',
            field=models.CharField(max_length=255),
        ),
    ]
