# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-11 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0120_merge_20180716_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='basefilenode',
            name='contents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
