# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-20 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0121_basefilenode_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='basefilenode',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
