# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-26 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0122_basefilenode_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='basefilenode',
            name='entities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
